### ISSUE TITLE
Resume to live after preroll ads on livestreams

### ISSUE THREAD

**Issue by ivo-toby** [meisterplayer/meisterplayer#25]
When playback resumes after prerolls the livestream is behind xx seconds (where xx is the amount of time the preroll played). 
Only livestreams without DVR

**Comment by FranklinWaller** [comment]
Waiting for https://github.com/meisterplayer/media-googleima/pull/3

**Comment by FranklinWaller** [comment]
Merged and bumped https://github.com/meisterplayer/media-googleima to v5.2.0 (https://github.com/meisterplayer/media-googleima/releases/tag/v5.2.0)
