### ISSUE TITLE
Livestreams zijn te pauzeren met de spatiebalk

### ISSUE THREAD

**Issue by cschalkwijk** [meisterplayer/meisterplayer#30]
Op het moment dat ik een livestream afspeel, krijg ik geen 'pauze' knop in de interface meer. Ik kan het afspelen echter nog wel pauzeren met een druk op de spatiebalk. Dit is, geloof ik, niet de bedoeling :)

**Comment by ivo-toby** [comment]
Also check forward/backward scrubbing with keyboard.

**Comment by jkroezen** [comment]
RTL ticket: https://jira.rtlnederland.nl/browse/VDO-1628 (for both pausing and scrubbing)

**Comment by ivo-toby** [comment]
Issue is fixed, please update player-html5player and ui-standardui-plugins

**Comment by ivo-toby** [comment]
Seems to still exist in new ui-html plugin

**Comment by ivo-toby** [comment]
Has this been released yet?

**Comment by FranklinWaller** [comment]
Yes

**Comment by ivo-toby** [comment]
Still seems to occur
