### ISSUE TITLE
Check for memoryleaks on streams with longer duration

### ISSUE THREAD

**Issue by ivo-toby** [meisterplayer/meisterplayer#32]
Both DASH and HLS need to be tested.

Firefox/DASH, Chrome/DASH, Edge/DASH may have performance issues after 45/60 minutes of playback.

**Comment by FranklinWaller** [comment]
Issue not part of meister player, moving to media-dash & media-hls https://github.com/meisterplayer/media-dash/issues/4 & https://github.com/meisterplayer/media-hls/issues/2

**Comment by ivo-toby** [comment]
Will take 2 milestones to check (and fix)

**Comment by FranklinWaller** [comment]
No results on this test, won't fix. Feel free to open this issue when there is more data on this issue.
