### ISSUE TITLE
Video stammers on Windows 8 > iE11

### ISSUE THREAD

**Issue by jkroezen** [meisterplayer/meisterplayer#34]
As shown/seen when RTL visited Triple. We could reproduce it on a Win8 laptop for AVOD content (tested with https://www.rtlxl.nl/?&_ga=2.12552562.774290345.1493989319-401448908.1493989273#!/voetbal-inside-343224/848f1bcf-3485-8a32-14a1-23f9e4317f96). 

This blocks the use of Meister on Win8 > IE11

**Comment by FranklinWaller** [comment]
Moving issue to https://github.com/meisterplayer/media-hls/issues/3 since it's a HLS related issue. 

Closing this issue.

**Comment by FranklinWaller** [comment]
Reopening for better view of issues

**Comment by FranklinWaller** [comment]
@jkroezen The URL is displaying flash at the moment on IE. Do you have an URL that uses the Meister player?

**Comment by jkroezen** [comment]
@thepauljones could you please help Franklin out with this?

**Comment by FranklinWaller** [comment]
Spoke with @thepauljones privately. 

This issue cannot be created on a test page (Since the page forces flash.) So we have to proxy the player_init script from RTL via Charles and enable meister instead of flash.

**Comment by FranklinWaller** [comment]
Ok so i've been testing and discovered the following:

- RTL Advertisement + RTL HLS video = Video stammers
- RTL Advertisement + Normal HLS Video = No stammering
- Normal Advertisment + RTL HLS video = Video stammers
- Normal Advertisment + Normal HLS Video = No stammering
- RTL HLS Video = No stammering
- Normal HLS Video = No stammering

It seems the combination of advertisements and the RTL HLS Video results in stammering of video playback. I'm not entirely sure why this happens.. But this is some of my results after testing..

I grabbed the normal HLS video from akamai: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

And the normal advertisment from Google's test ads: https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=

**Comment by ivo-toby** [comment]
Closing for now since it does not look like a issue with Meisterplayer.
