### ISSUE TITLE
Pre-load the WideVine service certificate

### ISSUE THREAD

**Issue by ivo-toby** [meisterplayer/meisterplayer#41]
**Chrome Browser**

The browser player application must set the service certificate to prevent a certificate request for each CDM session.

An alternative to executing the additional certificate request-response is to pre-load the service certificate, prior to any license request. This is recommended, as it avoids a round-trip to the license server.

Setting the service certificate to the application can be accomplished by using the EME’s setServiceCertificate API with the following considerations:

- setServiceCertificate should be called after the MediaKeys object is created, but before creating sessions with mediaKeys.createSession(...).
- The argument type is a BufferSource, which means either an ArrayBuffer or a Uint8Array will be accepted. A hex-encoded or base64-encoded string will not be accepted.
- The method returns a Promise that is resolved or rejected when the operation is complete. Sessions should be created after the Promise resolves.

**Comment by ivo-toby** [comment]
Please check : https://www.widevine.com/product_news.html

**Comment by ivo-toby** [comment]
Wait for news from Vualto

**Comment by Srivastava-Ankit** [comment]
@buttonfreak: How do we get the google widevine certificate form Exoplayer ?
