### ISSUE TITLE
UI on mobile not aligned, and too small on iOS

### ISSUE THREAD

**Issue by ivo-toby** [meisterplayer/meisterplayer#42]
The UI on ios is very small. On Android the UI is smaller in fullscreen. The embed-version is leading

**Comment by FranklinWaller** [comment]
![whatsapp image 2017-06-08 at 14 41 23](https://user-images.githubusercontent.com/5691892/26929078-ad6812d6-4c58-11e7-905f-fd56ef6b435c.jpeg)
