### ISSUE TITLE
Logo Overlay

### ISSUE THREAD

**Issue by ivo-toby** [meisterplayer/meisterplayer#48]
Not sure if this should be a cutomUI method or a plugin on its self; the ability to have a small overlay with a logo on the player (branding)

**Comment by FranklinWaller** [comment]
@buttonfreak Could you maybe help on how exactly this should look/be implemented? I'm not sure what to do exactly..

**Comment by FranklinWaller** [comment]
![maxresdefault](https://user-images.githubusercontent.com/5691892/27276870-cf259c9a-54dc-11e7-9c83-3fb537c79417.jpg)

Basically a watermark

**Comment by ivo-toby** [comment]
Yup, that's it

**Comment by FranklinWaller** [comment]
Done: https://github.com/meisterplayer/ui-watermark
