### ISSUE TITLE
audioOnly Multisource

### ISSUE THREAD

**Issue by ivo-toby** [meisterplayer/meisterplayer#55]
Change base-media to allow audio-streams with multiple formats. This should be enabled when `audioOnly`=true
Check for compatibility based on browser & OS.
First try OGG, then try AAC, then try MP3

**Comment by FranklinWaller** [comment]
The order will be determined how you give multisource the sources. First in will be first tried. The merge request is for when the stream is not able to play. Multisource will automatically try the next item in the list till it runs out of items to try.
